@startuml

' Settings
set separator ,
skinparam roundcorner 13
skinparam backgroundcolor #FFE299

' Structure
package src.main.java.org.example {
    package app {
        class SportsManagementSystem
    }

    package commands {
        class AddPlayerToTeamCommand
        class CreatePlayerCommand
        class CreateTeamCommand
        class CreateTournamentCommand
        class DeletePlayerCommand
        class DeleteTeamCommand
        class DeleteTournamentCommand
        class RemovePlayerFromTeamCommand
        class TournamentMatchmakingCommand
        class AddCurrentToTournamentCommand
        class RemoveCurrentFromTournamentCommand
        class ShowStatisticsCommand
        class ExitCommand
        class ListTournamentsCommand
        class LoginCommand
        class LogoutCommand
    }

    package models {
        enum Category
        abstract Command
        class Match <<deprecated>>
        class MatchList <<deprecated>>
        abstract Participant
        class ParticipantSet
        class Player
        enum Role
        class Team
        class Tournament
        class TournamentList
        class User
    }

    package views {
        class CLI
        class CommandView
        enum Error
        enum Message
        class ParticipantSetView
        class TournamentListView
    }
}

' Relationships
SportsManagementSystem <.up. CLI
SportsManagementSystem <.up. DatabaseReader

Command <|-down- AddCurrentToTournamentCommand
Command <|-down- AddPlayerToTeamCommand
Command <|-down- CreatePlayerCommand
Command <|-down- CreateTeamCommand
Command <|-down- CreateTournamentCommand
Command <|-down- DeletePlayerCommand
Command <|-down- DeleteTeamCommand
Command <|-down- DeleteTournamentCommand
Command <|-down- ExitCommand
Command <|-down- ListTournamentsCommand
Command <|-down- LoginCommand
Command <|-down- LogoutCommand
Command <|-down- RemoveCurrentFromTournamentCommand
Command <|-down- RemovePlayerFromTeamCommand
Command <|-down- ShowStatisticsCommand
Command <|-down- TournamentMatchmakingCommand

ParticipantSet o-down- Participant

Participant <|-down- Player

Participant <|-down- Team

Team o-- Player

Tournament *-down- Match

Player <.up. User

CLI *-down- ParticipantSet
CLI *-down- TournamentList
CLI *-up- java.util.Map
CLI *-up- java.util.List
CLI *-down- ExitCommand
CLI *-down- LoginCommand
CLI *-down- LogoutCommand
CLI *-down- CommandView
CLI <.up. Error
CLI <.up. Message
Message <.up.. System.out
Error <.up.. System.out
ParticipantSetView <.down. ParticipantSet
TournamentListView <.down. TournamentList

' Contents
SportsManagementSystem : + {static} void main(String[] args)
SportsManagementSystem : + void start()
SportsManagementSystem : + void pullInitialData(CLI cli)

Command : - String name
Command : - String usage
Command : - String description
Command : + Command(String name, String usage, String description)
Command : + {abstract} void run()
Command : + boolean matches(String commandName)
Command : + String getName()
Command : + String getUsage()
Command : + String getDescription()

CreatePlayerCommand : + CreatePlayerCommand(ParticipantSet participants)

ShowStatisticsCommand : + ShowStatisticsCommand(ParticipantSet participants)

ExitCommand : - boolean executed
ExitCommand : + ExitCommand()
ExitCommand : + boolean hasBeenExecuted()

@enduml
    
