@startuml

' Settings
set separator ,
skinparam roundcorner 13
skinparam backgroundcolor #FFE299

' Structure
package java {
    package lang {
        System.out
    }

    package util {
        interface List
        interface Map
        interface Set
        class ArrayList
        class HashMap
        class HashSet
        class LinkedList
    }
}

package src.main {
    package java.org.example {
        package app {
            class SportsManagementSystem
        }

        package commands {
            class PlayerCreateCommand
            class TeamCreateCommand
            class PlayerDeleteCommand
            class TeamDeleteCommand
            class TeamAddCommand
            class TeamRemoveCommand
            class TournamentCreateCommand
            class TournamentDeleteCommand
            class TournamentMatchmakingCommand
            class TournamentAddCommand
            class TournamentRemoveCommand
            class StatisticsShowCommand
            class LoginCommand
            class LogoutCommand
            class TournamentListCommand

            class ExitCommand
        }

        package drivers {
            abstract DatabaseReader
            abstract DatabaseWriter
            class DatabasePrinter

            class PlayersDatabaseReader
            class TeamsDatabaseReader
            class TournamentsDatabaseReader
            class UsersDatabaseReader
            class PlayersDatabaseWriter
            class TeamsDatabaseWriter
            class TournamentsDatabaseWriter
            class UsersDatabaseWriter
        }

        package models {
            enum Category
            abstract Command
            class Match <<deprecated>>
            class MatchList <<deprecated>>
            abstract Participant
            class ParticipantSet
            class Player
            enum Role
            class Team
            class Tournament
            class TournamentList
            class User
        }

        package views {
            class CLI
            class CommandView
            enum Error
            enum Message
            class ParticipantSetView
            class TournamentListView
        }
    }

    package resources {
        package database {
            object players.csv
            object teams.csv
            object tournaments.csv
            object users.csv
        }
    }
}

' Relationships
List <|-down- ArrayList
List <|-down- LinkedList
Map <|-down- HashMap
Set <|-down- HashSet

SportsManagementSystem <.up. CLI
SportsManagementSystem <.up. DatabaseReader

Command <|-down TournamentAddCommand
Command <|-down TeamAddCommand
Command <|-down PlayerCreateCommand
Command <|-down TeamCreateCommand
Command <|-down- TournamentCreateCommand
Command <|-down- PlayerDeleteCommand
Command <|-down- TeamDeleteCommand
Command <|-down- TournamentDeleteCommand
Command <|-down-- ExitCommand
Command <|-down-- TournamentListCommand
Command <|-down-- LoginCommand
Command <|-down-- LogoutCommand
Command <|-down--- TournamentRemoveCommand
Command <|-down--- TeamRemoveCommand
Command <|-down--- StatisticsShowCommand
Command <|-down--- TournamentMatchmakingCommand

ParticipantSet o-down- Participant

Participant <|-down- Player

Participant <|-down- Team

Team o-- Player

Tournament *-down- Match

Player <.up. User

CLI *-down- ParticipantSet
CLI *-down- TournamentList
CLI *-up---- HashMap
CLI *-up---- ArrayList
CLI *-down- ExitCommand
CLI *-down- LoginCommand
CLI *-down- LogoutCommand
CLI *-down- CommandView
CLI <.up. Error
CLI <.up. Message
Message <.up... System.out
Error <.up... System.out
ParticipantSetView <.down. ParticipantSet
TournamentListView <.down. TournamentList

' Contents
SportsManagementSystem : + {static} void main(String[] args)
SportsManagementSystem : + void start()
SportsManagementSystem : + void pullInitialData(CLI cli)

Command : - String name
Command : - String usage
Command : - String description
Command : + Command(String name, String usage, String description)
Command : + {abstract} void run()
Command : + boolean matches(String commandName)
Command : + String getName()
Command : + String getUsage()
Command : + String getDescription()

PlayerCreateCommand : + PlayerCreateCommand(ParticipantSet participants)

StatisticsShowCommand : + StatisticsShowCommand(ParticipantSet participants)

ExitCommand : - boolean executed
ExitCommand : + ExitCommand()
ExitCommand : + boolean hasBeenExecuted()

players.csv : field_1
players.csv : field_2
players.csv : field_3
players.csv : field_4

teams.csv : field_1
teams.csv : field_2
teams.csv : field_3
teams.csv : field_4

tournaments.csv : field_1
tournaments.csv : field_2
tournaments.csv : field_3
tournaments.csv : field_4

users.csv : field_1
users.csv : field_2
users.csv : field_3
users.csv : field_4

@enduml
    
