@startuml

package src.main.java.org.example {
    package controllers {
        class CommandFactory {
            +getCommand(): Command
            -createCommands()
        }
        class Controller {
            -getPlayerFromCurrentUser(): Player
            -getTeamFromPlayer(Player): Team
            +hasPermission(Role[]): boolean
            +login(String, String): Error
            +logout()
            +createPlayer(String, String, String): Error
            +deletePlayer(String): Error
            +isPlayerParticipatingInAInProgressTournament(String): Error
            +showStats(String[]): String
            +addToTeam(String, String): Error
            +createTeam(String): Error
            +deleteTeam(String): Error
            +removeFromTeam(String): Error
            +addToTournament(String, String): Error
            +createTournament(String, String, String, String, String): Error
            +deleteTournament(String): Error
            +listTournaments(): String
            -tournamentListing(Role): String
            +tournamentMatchmake(String, String, String[]): Error
            +removeFromTournament(String, String): Error
        }
        class Database
    }

    package models {
        enum Category
        interface Participant
        class Player implements Participant
        enum Role
        class Team implements Participant
        class Tournament
        class Match
        class User
    }

    package utils {
        class Console
        enum Error
    }

    package views {
        package commands {
            abstract Command
            interface CommandToExit
            class ConcreteCommand extends Command
            class ExitCommand extends Command
        }
        class CLI
        enum Message
    }
}

CommandFactory --> CLI
CommandFactory --> Controller
CLI --> Command
Command --> Controller

Console <-- CLI
Console <-- Command
Console <-- ConcreteCommand

Tournament +-- Match
Tournament o-- Match
Message --+ CLI
Message <.. CLI
CommandToExit <-- CLI
Role <-- User
Team <.. Category
Player <-- Category

Error <.. Command
Error <.. ConcreteCommand
Error <.. Controller
Error <.. CLI

Controller <-- User
Controller o-- Player
Controller o-- Team
Controller o-- Tournament
Controller o-- User
Controller <-- Database

@enduml