@startuml

package src.main.java.org.example {
    package controllers {
        class CommandFactory
        class Controller
        class Database
    }

    package models {
        enum Category
        interface Participant
        class Player implements Participant
        enum Role
        class Team implements Participant
        class Tournament
        class Match
        class User
    }

    package utils {
        class Console
        enum Error
    }

    package views {
        package commands {
            abstract Command
            class ConcreteCommand extends Command
        }
        class CLI
        enum Message
    }
}

Tournament +-- Match
CLI +-- Message

CommandFactory --> CLI
CommandFactory --> Controller
CLI --> Command
Command --> Controller

@enduml