@startuml

' Settings
set separator none
skinparam roundcorner 13
skinparam backgroundcolor #FFE299
allowmixing

' Structure
object "System.out" as sout

package src.main {
    package java.org.example {
        package commands {
            class PlayerCreateCommand
            class TeamCreateCommand
            class PlayerDeleteCommand
            class TeamDeleteCommand
            class TeamAddCommand
            class TeamRemoveCommand
            class TournamentCreateCommand
            class TournamentDeleteCommand
            class TournamentMatchmakingCommand
            class TournamentAddCommand
            class TournamentRemoveCommand
            class StatisticsShowCommand
            class LoginCommand
            class LogoutCommand
            class TournamentListCommand

            class ExitCommand
        }

        package drivers {
            abstract DatabaseReader
            abstract DatabaseWriter
            class DatabasePrinter

            class PlayersDatabaseReader
            class TeamsDatabaseReader
            class TournamentsDatabaseReader
            class UsersDatabaseReader
            class PlayersDatabaseWriter
            class TeamsDatabaseWriter
            class TournamentsDatabaseWriter
            class UsersDatabaseWriter
        }

        package models {
            enum Category
            abstract Command
            class Match <<deprecated>>
            class MatchList <<deprecated>>
            abstract Participant
            class ParticipantSet
            class Player
            enum Role
            class Team
            class Tournament
            class TournamentList
            class User
        }

        package views {
            class CLI
            class CommandView
            enum Error
            enum Message
            class ParticipantSetView
            class TournamentListView
        }

        class SportsManagementSystem
    }

    package resources {
        package "database" {
            file admins.csv
            file players.csv
            file teams.csv
            file tournaments.csv
        }

        file history.txt
    }
}

' Relationships
SportsManagementSystem <.up CLI
SportsManagementSystem <.up DatabaseReader

ParticipantSet o-- Participant

Participant <|-- Player
Participant <|-- Team

Player o- Team
Player --> User

Tournament *-. Match

Command <|-down TournamentAddCommand
Command <|-down TeamAddCommand
Command <|-down PlayerCreateCommand
Command <|-down TeamCreateCommand
Command <|-down TournamentCreateCommand
Command <|-down PlayerDeleteCommand
Command <|-down TeamDeleteCommand
Command <|-down TournamentDeleteCommand
Command <|-down ExitCommand
Command <|-down TournamentListCommand
Command <|-down LoginCommand
Command <|-down LogoutCommand

CLI *-- ParticipantSet
CLI *-- TournamentList
CLI --* HashMap
CLI --* ArrayList
CLI *-- ExitCommand
CLI *-- LoginCommand
CLI *-- LogoutCommand
CLI *-- CommandView
CLI ..> Error
CLI ..> Message
Message ..> sout
Error ..> sout
ParticipantSet <.. ParticipantSetView
TournamentList <.. TournamentListView

' Contents
SportsManagementSystem : + {static} void main(String[] args)
SportsManagementSystem : + void start()
SportsManagementSystem : + void pullInitialData(CLI cli)

Command : - String name
Command : - String usage
Command : - String description
Command : + Command(String name, String usage, String description)
Command : + {abstract} void run()
Command : + boolean matches(String commandName)
Command : + String getName()
Command : + String getUsage()
Command : + String getDescription()

PlayerCreateCommand : + PlayerCreateCommand(ParticipantSet participants)

StatisticsShowCommand : + StatisticsShowCommand(ParticipantSet participants)

ExitCommand : - boolean executed
ExitCommand : + ExitCommand()
ExitCommand : + boolean hasBeenExecuted()

@enduml
