package org.example.models;

public enum Error {
    NONE,
    UNKNOWN_COMMAND_ERROR,
    NO_PERMISSION,
    FORMAT_ERROR,
    PARSE_ERROR,
    PLAYER_ALREADY_EXISTS,
    ALREADY_LOGGED,
    NO_SUCH_USER,
    NOT_LOGGED_IN,
    EMPTY_STATEMENT
}
